import { expect, test } from '@playwright/test'

test('native slot copy/paste works across scenarios and leaves text editing alone', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await page.getByRole('button', { name: /Edit slot 5:/ }).click()
  await page.keyboard.press('Control+c')
  await expect(page.locator('.clipboard-status')).toContainText('Copied slot 5')
  await page.getByRole('button', { name: 'New scenario' }).click()
  await page.getByRole('button', { name: /Edit slot 1:/ }).click()
  await page.keyboard.press('Control+v')
  await expect(page.locator('.assigned-item')).toHaveCount(1)
  await expect(page.getByRole('checkbox', { name: 'Flex slot', exact: true })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Enable flex spots for this scenario', exact: true }).check()
  await page.getByRole('button', { name: /Edit slot 1:/ }).click()
  await page.keyboard.press('Control+v')
  await expect(page.locator('.assigned-item')).toHaveCount(5)
  await expect(page.getByRole('checkbox', { name: 'Flex slot', exact: true })).toBeChecked()
  await expect(page.getByRole('button', { name: 'Change binding 1', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Item 1 name', exact: true }).fill('Renamed gold')
  await page.reload()
  await page.getByRole('button', { name: /Edit slot 1:/ }).click()
  await expect(page.getByRole('textbox', { name: 'Item 1 name', exact: true })).toHaveValue('Renamed gold')

  const input = page.getByRole('textbox', { name: 'Custom item name' })
  await input.fill('Plain text')
  await input.selectText()
  await page.keyboard.press('Control+c')
  await input.fill('')
  await page.keyboard.press('Control+v')
  await expect(input).toHaveValue('Plain text')
  await expect(page.locator('.assigned-item')).toHaveCount(5)
  await page.getByRole('button', { name: /Edit slot 1:/ }).click()
  await page.keyboard.press('Control+v')
  await expect(page.locator('.clipboard-status')).toContainText('Copy a Hotbar Lab slot first')
  await expect(page.locator('.assigned-item')).toHaveCount(5)

  await page.locator('.scenario-trigger').click()
  await page.getByRole('dialog', { name: 'Choose scenario' }).getByRole('button', { name: 'Example MCSR setup Default' }).click()
  await page.getByRole('button', { name: /Edit slot 5:/ }).click()
  await expect(page.getByRole('textbox', { name: 'Item 1 name', exact: true })).toHaveValue('Gold Block')
  await page.getByRole('button', { name: /Edit slot 2:/ }).click()
  await page.keyboard.press('Control+c')
  await page.locator('.offhand-slot').click()
  await page.keyboard.press('Control+v')
  await expect(page.locator('.offhand-items')).toContainText('Axe')
})

test('individual flex controls, duplication and scenario import preserve item pools', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'New scenario' }).click()
  await page.getByRole('textbox', { name: 'Scenario name' }).fill('My destination')
  const flex = page.getByRole('checkbox', { name: 'Flex slot', exact: true })
  const scenarioFlex = page.getByRole('checkbox', { name: 'Enable flex spots for this scenario', exact: true })
  await expect(scenarioFlex).not.toBeChecked()
  await expect(flex).toBeDisabled()
  await scenarioFlex.check()
  await expect(flex).toBeEnabled()
  await flex.check()
  for (const name of ['Respawn Anchor', 'Glowstone']) {
    await page.getByLabel('Add from catalogue').fill(name)
    await page.getByTitle(`Add ${name}`, { exact: true }).click()
  }
  await expect(page.locator('.assigned-item')).toHaveCount(2)
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click()
  await expect(flex).toBeChecked()
  await expect(page.locator('.assigned-item')).toHaveCount(2)
  await scenarioFlex.uncheck()
  await expect(page.locator('.assigned-item')).toHaveCount(1)
  await expect(page.getByRole('textbox', { name: 'Item 1 name', exact: true })).toHaveValue('Respawn Anchor')
  await page.reload()
  await expect(scenarioFlex).not.toBeChecked()
  await expect(flex).toBeDisabled()

  const importButton = page.getByRole('button', { name: 'Import from another scenario', exact: true })
  const picker = page.getByRole('dialog', { name: 'Import from another scenario', exact: true })
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 960 })
    await importButton.click()
    await expect(page.getByRole('textbox', { name: 'Find a scenario' })).toBeFocused()
    await expect(picker.getByRole('button', { name: 'My destination (copy)', exact: true })).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`scenario-import-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(importButton).toBeFocused()
  }
  await importButton.click()
  await page.getByRole('textbox', { name: 'Find a scenario' }).fill('Example')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(picker).not.toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Scenario name' })).toHaveValue('My destination (copy)')
  await expect(page.locator('.assigned-item')).toHaveCount(5)
  await expect(scenarioFlex).toBeChecked()
  await expect(flex).toBeChecked()
  await expect(page.getByRole('button', { name: 'Change binding Z', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.assigned-item')).toHaveCount(5)
  await expect(flex).toBeChecked()
})
