import { expect, test } from '@playwright/test'

test('scenario picker, flex rules, saved defaults and player imports', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('checkbox', { name: 'Flex Spots', exact: true })).toBeChecked()
  await page.locator('.scenario-trigger').click()
  const picker = page.getByRole('dialog', { name: 'Choose scenario' })
  await expect(picker.getByRole('region', { name: 'Basics', exact: true }).getByRole('button')).toHaveCount(12)
  await expect(picker.getByRole('region', { name: 'Advanced', exact: true }).getByRole('button')).toHaveCount(27)
  await page.getByRole('textbox', { name: 'Find a scenario' }).fill('Ocean')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(picker).not.toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Scenario name' })).toHaveValue('Ocean overworld')
  await expect(page.getByRole('checkbox', { name: 'Flex Spots', exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Flex slot', exact: true })).toBeDisabled()
  await page.getByLabel('Add from catalogue').fill('Respawn Anchor')
  await page.getByTitle('Add Respawn Anchor').click()
  await page.getByLabel('Add from catalogue').fill('Glowstone')
  await page.getByTitle('Add Glowstone', { exact: true }).click()
  await expect(page.locator('.assigned-item')).toHaveCount(1)
  await expect(page.getByRole('textbox', { name: 'Item 1 name' })).toHaveValue('Glowstone')
  await page.getByRole('button', { name: 'Make default', exact: true }).click()
  await page.getByRole('textbox', { name: 'Scenario name' }).fill('Ocean practice')
  await expect(page.locator('.save-status')).toHaveText('Saved locally')
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Scenario name' })).toHaveValue('Ocean practice')
  await expect(page.getByRole('button', { name: /Edit slot 5: Glowstone/ })).toBeVisible()

  await page.getByRole('button', { name: 'doogile 12 scenarios', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Use player keybinds' }).check()
  await page.getByRole('button', { name: 'Import all 12', exact: true }).click()
  await expect(page.locator('.import-message')).toContainText('Imported 12 scenarios from doogile')
  await page.locator('.scenario-trigger').click()
  await page.getByRole('textbox', { name: 'Find a scenario' }).fill('doogile')
  await expect(picker.getByRole('button')).toHaveCount(12)
  await picker.getByRole('button', { name: 'doogile · Ocean overworld', exact: true }).click()
  await expect(page.getByRole('button', { name: /Edit slot 5:.*R/ })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Flex Spots', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  await expect(page.getByLabel('Editable preview')).toContainText('doogile · Ocean overworld')
  await page.getByRole('button', { name: 'Practice', exact: true }).click()
  await expect(page.locator('.prompt-card')).not.toHaveCount(0)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'lowkey 12 scenarios', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Use player keybinds' })).toBeDisabled()
  await page.getByRole('button', { name: 'infume 10 scenarios · Legacy', exact: true }).click()
  await expect(page.getByText(/Legacy snapshot:/)).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete scenario', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Scenario name' })).toHaveValue('Ocean practice')
})

test('popover keyboard dismissal, responsive layouts, and local asset rendering', async ({ page }) => {
  await page.goto('/')
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 960 })
    await page.locator('.scenario-trigger').click()
    await expect(page.getByRole('textbox', { name: 'Find a scenario' })).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 1440 || width === 390) await page.screenshot({ path: `artifacts/scenarios-picker-${width}.png` })
    await page.keyboard.press('Escape')
    await expect(page.locator('.scenario-trigger')).toBeFocused()
    await page.locator('.player-templates').scrollIntoViewIfNeeded()
    await expect(page.locator('.player-card img')).toHaveCount(6)
    await expect.poll(() => page.locator('.player-templates img').evaluateAll((images) => images.every((image) => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 1440 || width === 390) await page.locator('.player-templates').screenshot({ path: `artifacts/player-templates-${width}.png` })
  }
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.screenshot({ path: 'artifacts/scenarios-plan.png', fullPage: true })
})
