import { chromium } from '@playwright/test';
import { mkdir, copyFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const out = fileURLToPath(new URL('../docs/media/', import.meta.url));
const demo = fileURLToPath(new URL('../videos/hotbar-lab-demo/assets/', import.meta.url));
await mkdir(demo, {recursive:true});
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173');
await page.evaluate(()=>document.fonts.ready);
async function shot(name) {await page.mouse.move(1430,890); await page.screenshot({path:demo+name+'.png'}); if (['plan','practice','export'].includes(name)) await copyFile(demo+name+'.png',out+name+'.png');}
await shot('plan');
await page.getByRole('button',{name:/Edit slot 1:/}).click();
await shot('plan-slot');
await page.getByRole('button',{name:'Practice',exact:true}).click();
await page.getByRole('button',{name:'10',exact:true}).click();
await shot('practice');
await page.getByRole('button',{name:/Start session/}).click();
await page.waitForSelector('.practice-label');
await shot('practice-prompt');
await page.getByRole('button',{name:'Export',exact:true}).click();
await shot('export');
await page.getByRole('button',{name:'Customize slot 1',exact:true}).first().click();
await shot('export-customize');
await page.getByRole('button',{name:'Customize slot 1',exact:true}).first().click();
await page.getByRole('button',{name:'Download custom MPK',exact:true}).scrollIntoViewIfNeeded();
await shot('export-download');
const downloadWait=page.waitForEvent('download');
await page.getByRole('button',{name:'Download custom MPK',exact:true}).click();
const download=await downloadWait;
if(await download.failure()) throw new Error(await download.failure());
console.log('Verified browser download: '+download.suggestedFilename());
await page.locator('.export-grid').scrollIntoViewIfNeeded();
await shot('export-settings');
await copyFile(new URL('../public/favicon.svg',import.meta.url),demo+'favicon.svg');
await writeFile(demo+'capture-notes.json',JSON.stringify({viewport:{width:1440,height:900},source:'Local development app, clean browser context',pageErrors:errors,verifiedDownload:download.suggestedFilename()},null,2));
await browser.close();
if(errors.length) throw new Error(errors.join('\n'));
